apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: s3-call-file
  namespace: space-int-de
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "melgary/pyspark-final:3.5.3"
  imagePullPolicy: Always
  mainApplicationFile: s3a://mytest-bucket/dags/{{params.job}} #taxi.py
  sparkVersion: "3.5.3"
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.5.3
    serviceAccount: spark-operator-spark
    env:
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: s3-credentials
            key: AWS_ACCESS_KEY_ID
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: s3-credentials
            key: AWS_SECRET_ACCESS_KEY
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.5.3
    env:
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: s3-credentials
            key: AWS_ACCESS_KEY_ID
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: s3-credentials
            key: AWS_SECRET_ACCESS_KEY
  sparkConf:
    "spark.hadoop.fs.s3a.access.key": "29S27JQLBYGTQHMJ60OX"
    "spark.hadoop.fs.s3a.secret.key": "crKCWqBKUgubxNuHErdCG3cj0k84QZBDm3L2BEgN"
    "spark.hadoop.fs.s3a.endpoint": "http://192.168.1.152"
    "spark.hadoop.fs.s3a.path.style.access": "true"
    "spark.hadoop.fs.s3a.impl": "org.apache.hadoop.fs.s3a.S3AFileSystem"